test full pipeline

diff --git a/.github/workflows/be-pipeline.yml b/.github/workflows/be-pipeline.yml
--- a/.github/workflows/be-pipeline.yml
+++ b/.github/workflows/be-pipeline.yml
@@ -8,133 +8,138 @@ on:
 #        - 'be/**'
 
 jobs:
-#  Check-editorconfig:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout repo
-#        uses: actions/checkout@v4
-#
-#      - name: Setup python
-#      # infers python version from .python-version file
-#        uses: actions/setup-python@v4
-#
-#      - uses: editorconfig-checker/action-editorconfig-checker@main
-#      - name: Editor config check
-#        run: editorconfig-checker
-#
-#  Lint:
-#    name: Lint with Ruff & auto-commit fixes
-#    runs-on: ubuntu-latest
-#    permissions:
-#      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
-#      contents: write
-#    steps:
-#      - uses: actions/checkout@v3
-#      - uses: actions/setup-python@v4
-#
-#      - run: pip install ruff
-#      - run: |
-#          ruff check --fix
-#          ruff format .
-#
-#      - uses: stefanzweifel/git-auto-commit-action@v4
-#        with:
-#          commit_message: 'CI style fixes by ruff'
-#
-#  Markdown-lint:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout repo
-#        uses: actions/checkout@v4
-#
-#      - name: Lint with Markdown-lint
-#        uses: articulate/actions-markdownlint@v1
-#        with:
-#          config: .markdownlint.yml
-#          files: '**/*.md'
-#          ignore: node_modules
-#
-#  Check-hardcoded-secrets:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Shallow checkout
-#        uses: actions/checkout@v4
-#        # with:
-#        #   fetch-depth: 1
-#      - uses: gitleaks/gitleaks-action@v2
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#
-#  Unit-tests:
-#    needs: [Check-editorconfig, Lint, Markdown-lint, Check-hardcoded-secrets]
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout repo
-#        uses: actions/checkout@v4
-#
-#      - name: Setup python
-#        uses: actions/setup-python@v4
-#        with:
-#          cache: 'pip'
-#      - name: Install dependencies
-#        run: |
-#          python -m pip install --upgrade pip
-#          pip install -r ./be/test/requirements.txt || { echo "Failed to install test dependencies" ; exit 1; }
-#
-#      - name: Run unit tests with pytest
-#        working-directory: ./be
-#        run: |
-#          pytest test/test_app.py
-#
-#  Sonarcloud:
-#    name: SonarCloud scan
-#    needs: Unit-tests
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#        with:
-#          # Disabling shallow clone is recommended for improving relevancy of reporting
-#          fetch-depth: 0
-#
-#      - name: SonarCloud Scan
-#        uses: sonarsource/sonarcloud-github-action@master
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#        with:
-#          args: >
-#            -Dsonar.verbose=true
-#
-#  Snyk:
-#    name: Snyk security scan
-#    needs: Unit-tests
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@master
-#      - name: Setup python
-#        uses: actions/setup-python@v4
-#        with:
-#          cache: 'pip'
-#      - name: Install dependencies
-#        run: |
-#          python -m pip install --upgrade pip
-#          pip install -r ./be/src/requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
-#
-#      - name: Run Snyk to check for vulnerabilities
-#        uses: snyk/actions/python@master
-#        continue-on-error: true # To make sure that SARIF upload gets called
-#        env:
-#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-#        with:
-#          args: -d --severity-threshold=high --file=be/src/requirements.txt
-#
-#      - name: Upload result to GitHub Code Scanning
-#        uses: github/codeql-action/upload-sarif@v2
-#        with:
-#          sarif_file: snyk.sarif
+  editorconfig:
+    name: Check editorconfig
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
 
-  Build-push-docker-image:
-#    needs: [Unit-tests]
+      - name: Setup python
+      # infers python version from .python-version file
+        uses: actions/setup-python@v4
+
+      - uses: editorconfig-checker/action-editorconfig-checker@main
+      - name: Editor config check
+        run: editorconfig-checker
+
+  lint:
+    name: Lint with Ruff & auto-commit fixes
+    runs-on: ubuntu-latest
+    permissions:
+      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
+      contents: write
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+
+      - run: pip install ruff
+      - run: |
+          ruff check --fix
+          ruff format .
+
+      - uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: 'CI style fixes by ruff'
+
+  md-lint:
+    name: Lint for Markdowns
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Lint with Markdown-lint
+        uses: articulate/actions-markdownlint@v1
+        with:
+          config: .markdownlint.yml
+          files: '**/*.md'
+          ignore: node_modules
+
+  secrets:
+    name: Check for hardcoded secrets
+    runs-on: ubuntu-latest
+    steps:
+      - name: Shallow checkout
+        uses: actions/checkout@v4
+        # with:
+        #   fetch-depth: 1
+      - uses: gitleaks/gitleaks-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  tests:
+    name: BE Unit tests
+    needs: [editorconfig, lint, md-lint, secrets]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Setup python
+        uses: actions/setup-python@v4
+        with:
+          cache: 'pip'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r ./be/test/requirements.txt || { echo "Failed to install test dependencies" ; exit 1; }
+
+      - name: Run unit tests with pytest
+        working-directory: ./be
+        run: |
+          pytest test/test_app.py
+
+  sonar:
+    name: SonarCloud scan
+    needs: tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          # Disabling shallow clone is recommended for improving relevancy of reporting
+          fetch-depth: 0
+
+      - name: SonarCloud Scan
+        uses: sonarsource/sonarcloud-github-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          args: >
+            -Dsonar.verbose=true
+
+  snyk:
+    name: Snyk security scan
+    needs: tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@master
+      - name: Setup python
+        uses: actions/setup-python@v4
+        with:
+          cache: 'pip'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r ./be/src/requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/python@master
+        continue-on-error: true # To make sure that SARIF upload gets called
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          args: -d --severity-threshold=high --file=be/src/requirements.txt
+
+      - name: Upload result to GitHub Code Scanning
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: snyk.sarif
+
+  build-image:
+    name: Build, push and scan docker image
+    needs: [sonar, snyk]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
@@ -166,15 +171,6 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
-      - name: Print image-ref debug
-        run: |
-          echo "DOCKER_NAMESPACE=${{ vars.DOCKER_NAMESPACE }}"
-          echo "DOCKER_REPOSITORY=${{ vars.DOCKER_REPOSITORY }}"
-          echo "github.sha=${{ github.sha }}"
-          echo "repo+sha=${{ vars.DOCKER_REPOSITORY }}:sha-${{ github.sha }}"
-          echo "second repo+sha=${{vars.DOCKER_REPOSITORY}}:sha-${{github.sha}}"
-          echo "docker.io/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_REPOSITORY }}:sha-${{ github.sha }}"
 
       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@master
