replace linter

diff --git a/.github/workflows/be-pipeline.yml b/.github/workflows/be-pipeline.yml
--- a/.github/workflows/be-pipeline.yml
+++ b/.github/workflows/be-pipeline.yml
@@ -5,7 +5,7 @@ on:
 #        types: [ opened, synchronize, reopened ]
   push:
     paths:
-        - 'be/src/**'
+        - 'be/**'
 
 jobs:
   Check-editorconfig:
@@ -22,35 +22,52 @@ jobs:
       - name: Editor config check
         run: editorconfig-checker
 
-  Pylint:
+  Lint:
+    name: Lint with Ruff & commit
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v3
 
-      - name: Setup python
-        uses: actions/setup-python@v4
+      - uses: actions/setup-python@v4
+
+      - uses: chartboost/ruff-action@v1
         with:
-          cache: 'pip' # cache following pip dependencies
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pylint
-          pip install -r ./be/src/requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
-      - name: Run pylint
-        run: |
-          pylint $(git ls-files '*.py')
+          args: --check .
+          fix_args: --fix .
 
-  Black:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
-
-      - name: Run black formatter
-        uses: rickstaa/action-black@v1
+      - uses: stefanzweifel/git-auto-commit-action@v4
         with:
-          black_args: ". --check"
+          commit_message: 'style fixes by ruff'
+
+#  Pylint:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout repo
+#        uses: actions/checkout@v4
+#
+#      - name: Setup python
+#        uses: actions/setup-python@v4
+#        with:
+#          cache: 'pip' # cache following pip dependencies
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install pylint
+#          pip install -r ./be/src/requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
+#      - name: Run pylint
+#        run: |
+#          pylint $(git ls-files '*.py')
+#
+#  Black:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout repo
+#        uses: actions/checkout@v4
+#
+#      - name: Run black formatter
+#        uses: rickstaa/action-black@v1
+#        with:
+#          black_args: ". --check"
 
   Markdown-lint:
     runs-on: ubuntu-latest
